### ISSUE TITLE
Make the app a PWA

### ISSUE THREAD

**Issue by sanschristo** [sanschristo/continuous-learning#18]
As a consumer of the site,
I would like the app to be an installable, progressive web application,
so I can access the tools and information offline and have an icon on my desktop / home screen for easier access.

**Comment by alexkaufman06** [comment]
@sanschristo I just got it to work locally. The trick for me was to remove the `--base-href /continuous-learning/` from your npm `build` script when testing locally per Angular's instructions with the `http-server`. I'll make a PR for this with the build for GH in mind.

**Comment by alexkaufman06** [comment]
Looks like I'm unauthorized to commit, I think you'll have to add me as a contributor for me to push the branch up that I've got locally.

**Comment by sanschristo** [comment]
Ah, yeah I'll add you right now.  That's awesome you were able to get it to work!
